# Generated by Django 3.2.16 on 2023-10-10 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nextgis_common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_access_token', to=settings.AUTH_USER_MODEL, to_field='nextgis_guid'),
        ),
        migrations.AlterIndexTogether(
            name='accesstoken',
            index_together={('user', 'access_token_id')},
        ),
    ]
