# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextgis_common', '0002_auto_20161030_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_access_token', to=settings.AUTH_USER_MODEL, to_field='nextgis_guid'),
        ),
    ]
