# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nextgis_common', '0003_auto_20161103_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='access_token_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='access_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='refresh_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterIndexTogether(
            name='accesstoken',
            index_together=set([('user', 'access_token_id')]),
        ),
    ]
