# Generated by Django 3.2.16 on 2023-11-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextgis_common', '0003_auto_20231111_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
